
******************TESTING**************************
11/01/2022, 13:18:12
test_fruit_is_in (__main__.MyTests) ... ok
test_hola (__main__.MyTests) ... FAIL

======================================================================
FAIL: test_hola (__main__.MyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cratag/Documents/Programar/ALKEMY/UNIDAD11-Testing-2/Testing_txt_file/tests/test.py", line 11, in test_hola
    self.assertEqual(valid_word, to_check)
AssertionError: 'Hola' != 'Chau'
- Hola
+ Chau


----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
